# Used to identify the bot's owner in CTCP version replies. Has no effect on bot operation.
bot-owner: YourNameHere
bot:
    # The bot's nick.
    nick: FoxBot-Dev
    # The bot's ident. Will show as botnick!ident@host.com
    ident: bot
    # The name to show in /whois results.
    realname: FoxBot
server:
    # The server address.
    address: irc.seion.us
    # The server port.
    port: 6667
    # Should we use SSL?
    ssl: false
    # Should we accept an invalid SSL certificate?
    accept-invalid-ssl-cert: true
    # A password for connecting to the server, if required.
    password: password
    # List of channels for the bot to join on startup. Channel names must be enclosed in ''.
    channels:
    - '#foxdev'
    - '#foxbot'
auth:
    # Should we use nickserv?
    use-nickserv: true
    # The bot's nickserv password.
    nickserv-password: password
    # Do users have to be authed with nickserv to use bot commands?
    users-must-be-verified: true
    # Should we match users based on hostmasks? This mode is secure enough that you don't need to use "users-must-be-verified".
    match-users-by-hostmask: true
# Database settings for bot data storage.
database:
    # Database type. Can be sqlite or mysql.
    type: sqlite
    # These settings have no effect in sqlite mode.
    # The address of your MySQL server.
    host: localhost
    # The MySQL server port.
    port: 3306
    # The database name.
    name: foxbot
    # The username for the database.
    username: root
    # The password for the database.
    password: root
user-punishment:
    # Should the bot kick anyone who kicks the bot? NOT YET WORKING.
    punish-users-on-kick: true
    # What should the reason be when we punish a user? Set to '' to disable.
    punishment-kick-reason: You kick me, I kick you.
    # Time in seconds to unban users after a bot ban. Set to 0 to disable.
    unban-timer: 86400
misc:
    # Should we spam the console with debug info?
    debug: true
    # If the bot sees a message beginning with this, it is treated as a command. Can only be one character.
    command-prefix: '.'
    # Should the bot accept invites from users with bot.invite?
    auto-join-on-invite: true
    # Should the bot rejoin a channel after being kicked?
    auto-rejoin-on-kick: true
    # How long the bot will wait after being kicked to rejoin a channel.
    auto-rejoin-delay: 10
    # How long should the bot wait in seconds when kicking a user? (Used to prevent whois throttles on permission checks for both users).
    # WARNING: Setting this too low could get the bot throttled. Ask your network admins what the whois throttle rate is.
    kick-delay: 1000
    # Try for an alternative nick if the main one is taken.
    auto-nick-change: true
    # Should we auto-reconnect if the bot loses connection?
    auto-reconnect: true
    # How long the bot will wait to respond to events.
    message-delay: 0
    # Should we "munge" usernames to avoid pinging users?
    munge-usernames: true
    # If a channel is in this list, the bot will completely ignore any messages in it.
    ignored-channels:
    - '#annoyingchannel'
    # If a user joins one of these channels, the bot will send a greeting to them. Set this to [] if you don't want any greetings.
    channels-to-greet:
    - '#foxdev'
    - '#foxbot'
    # The message to send to the user if greetings are being used.
    # Key: {USER} = The user's nick, {CHANNEL} = The channel name, {CHANUSERS} = The amount of people in the channel.
    greeting-message: '&2Welcome to &c{CHANNEL}&2, &c{USER}&2. I am the channel''s help bot. There are currently &c{CHANUSERS}&2 people in this channel, however, some of them may be AFK, so if you have a question, please just ask it and wait patiently.&r'
    # Should we send the greeting as a notice rather than a message to the channel?
    send-greeting-as-notice: true
sounds:
    #The base URL to retrive sound clips from for the sound command.
    sound-url: 'https://dl.dropboxusercontent.com/u/70156340/'
    #The file name extension of the sounds in our remote sound database WITHOUT the "." (for example, if our sound files all ended with ".mp3" we would put mp3).
    sound-extension: 'mp3'
